### PR TITLE
Add Copy & Play song buttons.

### PR DESCRIPTION
**Pull request by SpaghettDev**
Adds a copy button besides the More button that copies the song's ID.
And shows the Play button that, evidently, plays the song.

Still need to figure out how to make the play song always be viewable since if you click it it just dissapears.
And need to make the copy button wrap around if the author's name is too long.

### CODE REVIEW

**Comment by josefv2** [comment]
Hello, there is no issue tab here but I inform this menu (1.39 version) does not open on Linux. Please look into it, thanks.

**Comment by SpaghettDev** [comment]
> Hello, there is no issue tab here but I inform this menu (1.39 version) does not open on Linux. Please look into it, thanks.

Are you using a windows-like subsystem (e.g. Proton)? Since this mod menu has Windows as its main target.
Now that I've come to think about it, I don't really know if using proton would work...

Anyway, does the menu inject fine? I've heard from another modding thread that proton is weird and won't let injectors inject into another process unless you use a fix (i think it's called steam-proton-fix or something of the likes...)

If it does inject, when you click the open button (TAB by default), does nothing appear?

Although this question would be suited to be asked in the discord server (probably, idk why maxnut has issues turned off, maybe due to spam?)...

**Comment by josefv2** [comment]
> Are you using a windows-like subsystem (e.g. Proton)? Since this mod menu has Windows as its main target. Now that I've come to think about it, I don't really know if using proton would work...

Yes, of course. I don't know more ways to run Windows games than Wine and Proton.
 
> Anyway, does the menu inject fine? I've heard from another modding thread that proton is weird and won't let injectors inject into another process unless you use a fix (i think it's called steam-proton-fix or something of the likes...)
> 
> If it does inject, when you click the open button (TAB by default), does nothing appear?

I'm not sure how to answer. Pressing Tab never shows the menu. I don't know if it's injected in first place. I dragged the files to the GD folder, after that, opened. I reinstalled the game several times too.

> Although this question would be suited to be asked in the discord server (probably, idk why maxnut has issues turned off, maybe due to spam?)...

I don't have Discord, would be great if issues were opened. I guess I can sign up as last resort, but I really want to stay away from social media.

**Comment by SpaghettDev** [comment]
@josefv2 well I can't help you since I don't use linux, but maybe try this: https://docs.google.com/document/d/1-itkJJt4p2s7Vd3Y0TwGRPG6xwWsu0bqE-U1axerq18/edit.
But if that doesn't work, your best bet is to join the discord, since it has a dedicated channel for support. But do keep in mind that Linux is unofficially supported! Only the community is of help, and not maxnut!

**Comment by SpaghettDev** [comment]
I feel like having the Copy button wrap around is unnecessary since it's very rare to have a song with an absurdly long author name, so I'm making this PR open for review.
@maxnut

**Comment by maxnut** [comment]
what does this do exactly

**Comment by SpektacleFR** [comment]
> I feel like having the Copy button wrap around is unnecessary since it's very rare to have a song with an absurdly long author name, so I'm making this PR open for review.

Although yes, it's rare, I do suggest implementing this.  While it's uncommon, it can still happen.  Of course, this is just me being a sucker for consistency, but do consider it :)

**Comment by SpaghettDev** [comment]
> > I feel like having the Copy button wrap around is unnecessary since it's very rare to have a song with an absurdly long author name, so I'm making this PR open for review.
> 
> Although yes, it's rare, I do suggest implementing this.  While it's uncommon, it can still happen.  Of course, this is just me being a sucker for consistency, but do consider it :)

I guess so...

**Comment by SpaghettDev** [comment]
> what does this do exactly

It adds a copy button besides the more button in the song widget, also makes the play song button visible (invisible by default for some reason)

**Comment by SpaghettDev** [comment]
Well apparently the game itself doesn't bother wrapping the More button around, so I too am not gonna bother doing it.

Geometry Dash Screenshot 2023 06 12 - 11 08 26 39

**Pull request merged**
