### PR TITLE
Fix the accumulated runs

### PR DESCRIPTION
**Pull request by SpaghettDev**
Fixes the accumulated runs, since after a certain threshold, it goes from "Best Run: 54%x3" to "x59" for example.
Also fixed the accumulated run when finishing a level, since if you beat it once it's "Best Run: 100%", but if you beat it again it is "Best Run: 100%x1"

### CODE REVIEW

**Comment by maxnut** [comment]
you probably didn't pull before pring because your commit resets my rainbow icon modifications

**Comment by SpaghettDev** [comment]
Yeah just noticed that, will fix when i have time...

**Comment by SpaghettDev** [comment]
rainbowPlayerVehicle wasn't actually defined in bools.h, nor did it have a button activating/deactivating it, so i implemented them

**Comment by SpaghettDev** [comment]
bump

**Comment by maxnut** [comment]
i completely removed rainbow player vehicle, i renemaed the variable and used it as something else. it isnt even implemented in playlayer

**Comment by SpaghettDev** [comment]
bump

**Pull request merged**
