### PR TITLE
extensions

### PR DESCRIPTION
**Pull request by Skyue1**
a window that allows you to see how many DLLs are loaded into the game.

### CODE REVIEW

**Comment by SpaghettDev** [comment]
this should defo be merged!

**Comment by Skyue1** [comment]
> this should defo be merged!

yeah

**Comment by maxnut** [comment]
sorry for not accepting but i was working on the api and now there is a method to do all the imgui begin trash in a single call, could you please update it with that?

**Comment by Skyue1** [comment]
> sorry for not accepting but i was working on the api and now there is a method to do all the imgui begin trash in a single call, could you please update it with that?

ok

**Pull request closed without merging**
